apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-worker-suggestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sn-worker-suggestion
  template:
    metadata:
      labels:
        app: sn-worker-suggestion
    spec:
      containers:
        - name: sn-worker-suggestion
          image: registry.emso.vn/sn-web:0.2.41
          resources:
            requests:
              cpu: "1.5"     
              memory: "1Gi"
          command: ["bundle", "exec"]
          args: ["sidekiq", "-c", "25", "-q", "suggestion"]
          envFrom:
            - configMapRef:
                name: sn-config
          ports:
            - name: streaming
              containerPort: 4000
      imagePullSecrets:
        - name: registry # Tên secret đã tạo
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: magnum.openstack.org/nodegroup
      #               operator: In
      #               values:
      #                 - ng-chat
      
