apiVersion: batch/v1
kind: Job
metadata:
  name: sample-api-migrate
  labels:
    app.kubernetes.io/name: sample-api-migrate
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-api-migrate
    spec:
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: sample-api
        image: docker.io/geshan/band-api:latest
        imagePullPolicy: IfNotPresent
        name: main
      restartPolicy: Never
