apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sample-api
    process: web
  name: sample-api-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-api
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-api
        process: web
    spec:
      containers:
      - env:
        - name: PORT
          value: "3000"
        envFrom:
        - configMapRef:
            name: sample-api
        image: wowai/samle-api:latest
        imagePullPolicy: IfNotPresent
        name: sample-api-web
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health_check/healthcheck
            port: 300
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 350m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 128Mi
      restartPolicy: Always
