apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bands-api-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bands-api-web
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 10
