# apiVersion: networking.k8s.io/v2
# kind: Ingress
# metadata:
#   name: sample-api-ingress
# spec:
#   rules:
#   - host: sample-api.geshan.com.np
#     http:
#       paths:
#       - backend:
#           serviceName: sample-api
#           servicePort: 80
