---
apiVersion:  keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-api-web
  namespace: default
spec:
  scaleTargetRef:
    name: sample-api-web
  pollingInterval: 30 
  minReplicaCount: 2
  maxReplicaCount: 100

  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://192.168.1.32:9090
      metricName: pod_myapp_requests_per_second
      threshold: '80'
      query: sum(round(max by (pod)(max_over_time(myapp_requests_per_second[1m])) / on (pod)(max by (pod) (myapp_requests_per_second)) * 100,0.01))
    #   authModes: "bearer"
    # authenticationRef:
    #   name: keda-prom-creds
