---
# nginx.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
          - containerPort: 80

---
#nginx-service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "true"
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
  selector:
    name: nginx
---
#nginx-hpa.yaml 
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment     # Áp dụng HPA cho Deployment
    name: nginx
  minReplicas: 1   # Số pod scale nhỏ nhất
  maxReplicas: 10  # Số pod scale lớn nhất
 
  # thực hiện scale khi CPU hoạt động ở mức 10%
  # so với CPU mà pod được xác định
  # (ở trên mình để cpu của pod là 100m)
  targetCPUUtilizationPercentage: 10 
#kubectl run --generator=run-pod/v1 -it --rm load-generator --image=busybox /bin/sh
# while true; do wget -q -O- http://172.16.10.100:31080; done
# kubectl get hpa
# kubectl get pods
# https://www.alibabacloud.com/help/en/ack/ack-managed-and-ack-dedicated/user-guide/configure-horizontal-pod-autoscaling-for-multiple-applications-based-on-the-metrics-of-the-nginx-ingress-controller
