# export KUBECONFIG=./kubeconfig-cluster1.yaml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.3.0.0/16
  serviceSubnet: 172.18.0.0/24
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32043
        hostPort: 32043
      - containerPort: 31235
        hostPort: 31235
      - containerPort: 31236
        hostPort: 31236
  - role: worker
  - role: worker