# export KUBECONFIG=./kubeconfig-cluster1.yaml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
 # pod 网段
  podSubnet: "10.24.0.0/16"
  # service 网段
  serviceSubnet: "10.25.0.0/16"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32043
        hostPort: 32043
      - containerPort: 31237
        hostPort: 31237
      - containerPort: 31236
        hostPort: 31236
  - role: worker
  - role: worker