# export KUBECONFIG=./kubeconfig-cluster2.yaml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
 # pod 网段
  podSubnet: "10.26.0.0/16"
  # service 网段
  serviceSubnet: "10.27.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker