---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  podSubnet: 10.2.0.0/16
  serviceSubnet: 172.18.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker