version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=Qy6VTnREtzwBbzgvxY2LJA5QQwFNex4wUtj2qNTTnSXtHykdZM
      - RAILS_ENV=development
      - DATABASE_NAME=zrgyfclw
      - DATABASE_USER=zrgyfclw
      - DATABASE_PASSWORD=5br8zs-McuU5ISx_cp5il97O183_FgYh
      - DATABASE_HOST=topsy.db.elephantsql.com
      - DATABASE_PORT=5432
