apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-server
  labels:
    app: git-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-server
  template:
    metadata:
      labels:
        app: git-server
    spec:
      containers:
        - name: git-server
          image: pascalgn/git-server-docker:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  labels:
    app: git-server
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: git-server
