apiVersion: v1
kind: Service
metadata:
  annotations:
    loadbalancer.openstack.org/class: "cmc-loadbalancer-public"
  name: pt-rtmp
spec:
  selector:
    app: sn-pt
  ports:
    - name: rtmp
      protocol: TCP
      port: 1935
      targetPort: 1935
  type: LoadBalancer