debug:
  enabled: true
nodeinit:
  enabled: true
  restartPods: true
kubeProxyReplacement: partial
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
ipam:
  mode: kubernetes
bpf:
  masquerade: false
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
cluster:
  id: 1
  name: kind-1
clustermesh:
  useAPIServer: true
  config:
    enabled: true
    clusters:
    - name: kind-1
      port: 2379
      ips:
      - 172.16.0.41
    - name: kind-2
      port: 2379
      ips:
      - 172.16.0.113
    - name: kind-3
      port: 2379
      ips:
      - 172.16.0.59
    - name: kind-4
      port: 2379
      ips:
      - 172.16.0.81
    - name: kind-5
      port: 2379
      ips:
      - 172.16.0.67
  apiserver:
    tls:
      auto:
        enabled: false
    service:
      type: NodePort
      loadBalancerIP: 172.16.0.41