debug:
  enabled: true
nodeinit:
  enabled: true
  restartPods: true
kubeProxyReplacement: partial
hostServices:
  enabled: false
externalIPs:
  enabled: true
nodePort:
  enabled: true
hostPort:
  enabled: true
ipam:
  mode: kubernetes
bpf:
  masquerade: false
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
cluster:
  id: 1
  name: cluster1
clustermesh:
  useAPIServer: true
  config:
    enabled: true
    clusters:
    - name: cluster1
      port: 2379
      ips:
      - 172.16.0.41
      tls:
        # tls.crt from clustermesh-apiserver-remote-cert secret in Cluster 1
        # tls.key from clustermesh-apiserver-remote-cert secret in Cluster 1
        cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJuVENDQVVLZ0F3SUJBZ0lVQXNOa3BTaVBLdlBLampuM0FUczJjUjZ4RkFBd0NnWUlLb1pJemowRUF3SXcKRkRFU01CQUdBMVVFQXhNSlEybHNhWFZ0SUVOQk1CNFhEVEkwTURrd01qRXpNREV3TUZvWERUSTNNRGt3TWpFegpNREV3TUZvd0VURVBNQTBHQTFVRUF4TUdjbVZ0YjNSbE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEClFnQUVzR0lKdTlZbFZjSVNEZ256dUw0U0drd1V1d1JISjY3NlptME90RFk2NW5MRG15TkVoYTdlZ05aS1A0K3IKUTlRbk9FcWovZHg1S3psRnhpVDVGbFQ0RWFOMU1ITXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTQpNQW9HQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGQ0ZQbzNlZDNjQjZTZHJTCnhoRDdxUTRSbjQvRU1COEdBMVVkSXdRWU1CYUFGRjRzYlEwSjdaUUFUTXJ6SkFPOVJKOUJFZGQ2TUFvR0NDcUcKU000OUJBTUNBMGtBTUVZQ0lRRDR0bUllMVF0UHBsaWJDKzhSUzJ4UElDLzBUYzRCcVZHWnZxYmNDWGpmY0FJaApBTnlYbHc1YWhUdEtuN2hjMmZQcTFDRUp0UmNLaDMxUTFuaVYzZjRPY1g1MQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU45dU1xQVIyUDFEbS9vbDAxVFJoYWJqcFRBZjVwTVE4OFRDRElpeWFsL1lvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFc0dJSnU5WWxWY0lTRGduenVMNFNHa3dVdXdSSEo2NzZabTBPdERZNjVuTERteU5FaGE3ZQpnTlpLUDQrclE5UW5PRXFqL2R4NUt6bEZ4aVQ1RmxUNEVRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    - name: cluster2
      port: 2379
      ips:
      - 172.16.0.113
      tls:
        #kubectl get secret clustermesh-apiserver-remote-cert -n kube-system -o yaml
        # tls.crt from clustermesh-apiserver-remote-cert secret in Cluster 1
        # tls.key from clustermesh-apiserver-remote-cert secret in Cluster 1
        cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJtekNDQVVLZ0F3SUJBZ0lVR2Y1N0pEem9TZE9STGNTREdpSS9DNEdQLzNZd0NnWUlLb1pJemowRUF3SXcKRkRFU01CQUdBMVVFQXhNSlEybHNhWFZ0SUVOQk1CNFhEVEkwTURrd01qRXlOVGt3TUZvWERUSTNNRGt3TWpFeQpOVGt3TUZvd0VURVBNQTBHQTFVRUF4TUdjbVZ0YjNSbE1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEClFnQUUvSlZReWEwMnFrWm9Mby9BZDlGV0ZmUE5Oc3FUM0JQVGdGSnJyWXk4TE83WUwwVXZLdlEzVUEvV0NGWDIKR01LQ29rVDNWL2VDeTBiN09vM3lUSlF3a2FOMU1ITXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CTUdBMVVkSlFRTQpNQW9HQ0NzR0FRVUZCd01DTUF3R0ExVWRFd0VCL3dRQ01BQXdIUVlEVlIwT0JCWUVGTDYySksrYnh1TTNlaVFHCnprZkljTkJVYzlkT01COEdBMVVkSXdRWU1CYUFGTXhMUlk5aWdSSEtlUEc1K2J4M1BLSUl4bVdnTUFvR0NDcUcKU000OUJBTUNBMGNBTUVRQ0lESFdwNXFtUVk1TDJwWXdkbWR2VG9JOW1hNjV1Mk1ESjdJRy9hbWVrRmhSQWlCegoyS2dLWWwrWjZUNWVML1AvdmkyT2xnTkJPSXhwdkpZdVppa0JUemlHVWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUowWGlqK2ZGOENidmNMYmhWdGJoK1VuUE1HZ0NJTkNJYVFOekMxMlEwZnBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFL0pWUXlhMDJxa1pvTG8vQWQ5RldGZlBOTnNxVDNCUFRnRkpycll5OExPN1lMMFV2S3ZRMwpVQS9XQ0ZYMkdNS0Nva1QzVi9lQ3kwYjdPbzN5VEpRd2tRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=

    # - name: kind-3
    #   port: 2379
    #   ips:
    #   - 172.16.0.59
    # - name: kind-4
    #   port: 2379
    #   ips:
    #   - 172.16.0.81
    # - name: kind-5
    #   port: 2379
    #   ips:
    #   - 172.16.0.67
  apiserver:
    tls:
      auto:
        enabled: false
    service:
      type: NodePort
      loadBalancerIP: 172.16.0.41
  # apiserver:
  #   tls:
  #     auto:
  #       method: cronJob
  #     ca:
  #       # ca.crt from the cilium-ca secret in Cluster 1 (important - not Cluster 2)
  #       cert: "<base64-encoded-cert>"
  #       # ca.key from the cilium-ca secret in Cluster 1 (important - not Cluster 2)
  #       key: "<base64-encoded-key>"
  #   service:
  #     type: LoadBalancer