kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster1
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.4.0.0/16"
  serviceSubnet: "10.5.0.0/16"
  # apiServerAddress: "172.16.0.41"
  # apiServerPort: 6443