kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: "10.6.0.0/16"
  serviceSubnet: "10.7.0.0/16"
  # apiServerAddress: "172.16.0.113"
  # apiServerPort: 6443