---
apiVersion: v1
kind: Service
metadata:
  name: global-base
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: global-base
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-base
spec:
  selector:
    matchLabels:
      name: global-base
  replicas: 2
  template:
    metadata:
      labels:
        name: global-base
    spec:
      containers:
      - name: global-base
        image: wowai/go-rest-postgres
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html/
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
      volumes:
        - name: html
          configMap:
            name: rebel-base-response
            items:
              - key: message
                path: index.html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rebel-base-response
data:
  message: "{\"Galaxy\": \"Alderaan\", \"Cluster\": \"Cluster-1\"}\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-wing
spec:
  selector:
    matchLabels:
      name: x-wing
  replicas: 2
  template:
    metadata:
      labels:
        name: x-wing
    spec:
      containers:
      - name: x-wing-container
        image: docker.io/cilium/json-mock:1.2
        livenessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
        readinessProbe:
          exec:
            command:
            - curl
            - -sS
            - -o
            - /dev/null
            - localhost
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: global-base
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment     # Áp dụng HPA cho Deployment
    name: global-base
  minReplicas: 1   # Số pod scale nhỏ nhất
  maxReplicas: 10  # Số pod scale lớn nhất