apiVersion: v1
kind: Service
metadata:
  name: global-service-base
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    name: global-service-base