# export KUBECONFIG=./kubeconfig-cluster1.yaml
---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
 # pod 网段
  podSubnet: "10.20.0.0/16"
  # service 网段
  serviceSubnet: "10.21.0.0/16"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32042
        hostPort: 32042
      - containerPort: 31234
        hostPort: 31234
      - containerPort: 31235
        hostPort: 31235
  - role: worker
  - role: worker