apiVersion: apps/v1
kind: Deployment
metadata:
  name: sn-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sn-marketplace
  template:
    metadata:
      labels:
        app: sn-marketplace
    spec:
      containers:
        - name: sn-marketplace
          image: quoiwowai/sn-marketplace
          # resources:
          #   requests:
          #     cpu: "2"     
          #     memory: "1.5Gi"
          resources:
            requests:
              cpu: "0.5"
              memory: 700Mi
            limits:
              cpu: "2.5"
              memory: 2Gi
          envFrom:
            - configMapRef:
                name: marketplace-config
          ports:
            - name: marketplace
              containerPort: 3000
      # imagePullSecrets:
      #   - name: registry # Tên secret đã tạo
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: magnum.openstack.org/nodegroup
      #               operator: In
      #               values:
      #                 - ng-chat

