apiVersion: v1
kind: ConfigMap
metadata:
  name: peertube-runner-config
data:
  config.toml: |
    [jobs]
    concurrency = 2

    [ffmpeg]
    threads = 2
    nice = 20

    [[registeredInstances]]
    url = "https://pt3.emso.vn"
    runnerToken = "ptrt-02e4ed0f-6fef-4dae-85f6-2645cc92a6a9"
    runnerName = "my-runner-1"